export default {
  initializeVisibility: () => {
    storeValue("input1Visible", true);
    storeValue("button2Visible", true);
		
		if(videolinks2.text){
			storeValue("input2Visible",true);
		}
		else{
			storeValue("input2Visible",false);
		}
		if(videolinks3.text){
			storeValue("input3Visible",true);
		}
		else{
			storeValue("input3Visible",false);
		}
		if(videolinks4.text){
			storeValue("input4Visible",true);
		}
		else{
			storeValue("input4Visible",false);
		}
		if(videolinks5.text){
			storeValue("input5Visible",true);
		}
		else{
			storeValue("input5Visible",false);
		}
		if(videolinks6.text){
			storeValue("input6Visible",true);
		}
		else{
			storeValue("input6Visible",false);
		}
		if(videolinks7.text){
			storeValue("input7Visible",true);
		}
		else{
			storeValue("input7Visible",false);
		}
		if(videolinks8.text){
			storeValue("input8Visible",true);
		}
		else{
			storeValue("input8Visible",false);
		}
		if(videolinks9.text){
			storeValue("input9Visible",true);
		}
		else{
			storeValue("input9Visible",false);
		}
		if(videolinks10.text){
			storeValue("input10Visible",true);
		}
		else{
			storeValue("input10Visible",false);
		}
		if(gemstonenameCopy.selectedOptionLabel){
			storeValue("gemstone2Visible",true);
		}
		else{
			storeValue("gemstone2Visible",false);
		}
		if(gemstonenameCopy1.selectedOptionLabel){
			storeValue("gemstone3Visible",true);
		}
		else{
			storeValue("gemstone3Visible",false);
		}
		if(gemstonenameCopy2.selectedOptionLabel){
			storeValue("gemstone4Visible",true);
		}
		else{
			storeValue("gemstone4Visible",false);
		}
		if(gemstonenameCopy3.selectedOptionLabel){
			storeValue("gemstone5Visible",true);
		}
		else{
			storeValue("gemstone5Visible",false);
		}
		if(gemstonenameCopy4.selectedOptionLabel){
			storeValue("gemstone6Visible",true);
		}
		else{
			storeValue("gemstone6Visible",false);
		}
		if(gemstonenameCopy5.selectedOptionLabel){
			storeValue("gemstone7Visible",true);
		}
		else{
			storeValue("gemstone7Visible",false);
		}
		if(gemstonenameCopy6.selectedOptionLabel){
			storeValue("gemstone8Visible",true);
		}
		else{
			storeValue("gemstone8Visible",false);
		}
		if(gemstonenameCopy7.selectedOptionLabel){
			storeValue("gemstone9Visible",true);
		}
		else{
			storeValue("gemstone9Visible",false);
		}
		if(gemstonenameCopy8.selectedOptionLabel){
			storeValue("gemstone10Visible",true);
		}
		else{
			storeValue("gemstone10Visible",false);
		}
		if(stonesettingnameCopy.selectedOptionLabel){
			storeValue("stone2Visible",true);
		}
		else{
			storeValue("stone2Visible",false);
		}
		if(stonesettingnameCopyCopy.selectedOptionLabel){
			storeValue("stone3Visible",true);
		}
		else{
			storeValue("stone3Visible",false);
		}
		if(stonesettingnameCopyCopy1.selectedOptionLabel){
			storeValue("stone4Visible",true);
		}
		else{
			storeValue("stone4Visible",false);
		}
		if(stonesettingnameCopyCopy2.selectedOptionLabel){
			storeValue("stone5Visible",true);
		}
		else{
			storeValue("stone5Visible",false);
		}
		if(stonesettingnameCopyCopy3.selectedOptionLabel){
			storeValue("stone6Visible",true);
		}
		else{
			storeValue("stone6Visible",false);
		}
		if(stonesettingnameCopyCopy4.selectedOptionLabel){
			storeValue("stone7Visible",true);
		}
		else{
			storeValue("stone7Visible",false);
		}
		if(stonesettingnameCopyCopy5.selectedOptionLabel){
			storeValue("stone8Visible",true);
		}
		else{
			storeValue("stone8Visible",false);
		}
		if(stonesettingnameCopyCopy6.selectedOptionLabel){
			storeValue("stone9Visible",true);
		}
		else{
			storeValue("stone9Visible",false);
		}
		if(stonesettingnameCopyCopy7.selectedOptionLabel){
			storeValue("stone10Visible",true);
		}
		else{
			storeValue("stone10Visible",false);
		}
		
		if(attributenameCopy.selectedOptionLabel){
			storeValue("attribute2Visible",true);
		}
		else{
			storeValue("attribute2Visible",false);
		}
		if(attributenameCopyCopy.selectedOptionLabel){
			storeValue("attribute3Visible",true);
		}
		else{
			storeValue("attribute3Visible",false);
		}
		if(attributenameCopyCopy1.selectedOptionLabel){
			storeValue("attribute4Visible",true);
		}
		else{
			storeValue("attribute4Visible",false);
		}
		if(attributenameCopyCopy2.selectedOptionLabel){
			storeValue("attribute5Visible",true);
		}
		else{
			storeValue("attribute5Visible",false);
		}
		if(attributenameCopyCopy3.selectedOptionLabel){
			storeValue("attribute6Visible",true);
		}
		else{
			storeValue("attribute6Visible",false);
		}
		if(attributenameCopyCopy4.selectedOptionLabel){
			storeValue("attribute7Visible",true);
		}
		else{
			storeValue("attribute7Visible",false);
		}
		if(attributenameCopyCopy5.selectedOptionLabel){
			storeValue("attribute8Visible",true);
		}
		else{
			storeValue("attribute8Visible",false);
		}
		if(attributenameCopyCopy6.selectedOptionLabel){
			storeValue("attribute9Visible",true);
		}
		else{
			storeValue("attribute9Visible",false);
		}
		if(attributenameCopyCopy7.selectedOptionLabel){
			storeValue("attribute10Visible",true);
		}
		else{
			storeValue("attribute10Visible",false);
		}
  }
}
